When navigating to http:/public-ip:15672 everything works but:

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>   crasher:

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>     initial call: cowboy_stream_h:request_process/3

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>     pid: <0.826.0>

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>     registered_name: []

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>     exception exit: {{request_error,

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>                          {header,<<"authorization">>},

2024-01-16 21:37:11.386120+00:00 [error] <0.826.0>                          'Malformed header. Please consult the relevant specification.'},

[..]
2024-01-16 21:49:12.742683+00:00 [warning] <0.1239.0> HTTP access denied: user 'guest' - invalid credentials


It is only 1 time

https://github.com/docker-library/rabbitmq/issues/433

You are right. It is really the permission problem caused by the setting of the hostname property.
